### ISSUE TITLE
request: (discord.js-utilities): `PaginatedMessage` interaction replies

### ISSUE THREAD

**Issue by 1chiSensei** [sapphiredev/utilities#218] opened 2021-11-16 00:40 UTC
**Is your feature request related to a problem? Please describe.**
I want to use `PaginatedMessage` for slash commands.

**Describe the solution you'd like**
Currently, it doesnt work if you pass `interaction.fetchReply()`.

**Describe alternatives you've considered**
Support interaction replies.

**Comment by favna** [comment] 2021-11-16 08:28
Right now I'd have no good way to test this because sapphire doesn't officially support slash commands yet. So if you want this feature to land before such time, please provide a repository with an easy to use bot that I can use for reproduction & testing.

**Comment by favna** [comment] 2022-01-17 18:48
Updating this issue, I started working on https://github.com/favware/dragonite which will be an interaction based pokedex bot that will make use of the PM class so as part of that project I will be updating the class here too.

**Comment by favna** [comment] 2022-01-22 12:55
This was added in #246 and released in @sapphire/discord.js-utilities@4.4.0

**Closed by favna** 2022-01-22 12:55 UTC
Labels: Meta: Feature
